# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: COMS / VistA-RPC Documentation
email: barlowm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site attempts to document the VistA RPC calls made by the COMS (Chemotherapy Order Management System) developed by dbITPro for the Department of Veteran Affairs


baseurl: "/VistA_RPC" # the subpath of your site, e.g. /blog
url: "http://mwbarlow.com" # the base hostname & protocol for your site
port: 4000
twitter_username: MWBInJersey
github_username:  barlowm

# Build settings
markdown: kramdown
